// <auto-generated />
namespace Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addblogurl3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addblogurl3));
        
        string IMigrationMetadata.Id
        {
            get { return "202001301302210_addblogurl3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
