// <auto-generated />
namespace Security.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeJoin : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeJoin));
        
        string IMigrationMetadata.Id
        {
            get { return "202001311349330_removeJoin"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
